### ISSUE TITLE
Add usergroups methods

### ISSUE THREAD

**Issue by jpvillaisaza** [MercuryTechnologies/slack-web#26]
- [ ] `usergroups.create`
- [ ] `usergroups.disable`
- [ ] `usergroups.enable`
- [ ] `usergroups.list`
- [ ] `usergroups.update`

**Comment by jpvillaisaza** [comment]
Reopen if/when needed.

**Comment by apolishch** [comment]
I take it this isn't on the roadmap then? :(

**Comment by jpvillaisaza** [comment]
@apolishch I closed all issues with the idea of reopening when needed, so feel free to reopen.
