### ISSUE TITLE
Expose HasManager and HasToken typeclass methods to we can define instances on our own env types

### ISSUE THREAD

**Issue by ozataman** [MercuryTechnologies/slack-web#53]

**Comment by emmanueltouzery** [comment]
can you check whether https://github.com/jpvillaisaza/slack-web/pull/55 would help?

**Comment by emmanueltouzery** [comment]
PR #55 was now merged to master, I think it fixes the issue. It'll get released very soon together with the servant 0.13 support, so closing this bug.

**Comment by ozataman** [comment]
Hi there - I’m away from my computer at the moment but you may want to look at my personal fork to see the couple changes I needed to be able to use your library. There was one other thing if memory serves right. 
		
		

		
	




On Tue, Feb 13, 2018 at 12:31 PM -0500, "emmanueltouzery" <notifications@github.com> wrote:












PR #55 was now merged to master, I think it fixes the issue. It'll get released very soon together with the servant 0.13 support, so closing this bug.

**Comment by emmanueltouzery** [comment]
hmm I see:

    instance Exception SlackClientError

I'm not very familiar with this or why it would be needed. Maybe make a PR explaining why it's needed, and this can be discussed there? Unless if  @jpvillaisaza is more familiar with that.

**Comment by ozataman** [comment]
It’s pretty simple: I want to be able to throw exceptions rather than deal with the either in certain use cases. The instance allows for that - fairly standard practice in Haskell. 
		
		

		
	




On Tue, Feb 13, 2018 at 1:10 PM -0500, "emmanueltouzery" <notifications@github.com> wrote:












hmm I see:
instance Exception SlackClientError



I'm not very familiar with this or why it would be needed. Maybe make a PR explaining why it's needed, and this can be discussed there? Unless if  @jpvillaisaza is more familiar with that.

**Comment by emmanueltouzery** [comment]
@jpvillaisaza do we add that `instance Exception SlackClientError`? I can make a PR and add it to the upcoming release for servant-0.13. I have no opinion.

**Comment by jpvillaisaza** [comment]
@emmanueltouzery Go ahead, sounds good. Here's @ozataman's change: https://github.com/jpvillaisaza/slack-web/commit/1a83aea5132241b1b90ab8acbc8ad88843d796c8

**Comment by emmanueltouzery** [comment]
I'm sorry, another thing. I see that this change also adds `derive Typeable` for `SlackClientError`. Once again I have no opinion. Do I add it too?

**Comment by jpvillaisaza** [comment]
@emmanueltouzery I think that should be fine too.

**Comment by ozataman** [comment]
Thanks, appreciate it!
		
		

		
	




On Thu, Feb 15, 2018 at 12:42 AM -0500, "emmanueltouzery" <notifications@github.com> wrote:












Closed #53 via 92a4fae.
