### ISSUE TITLE
Test against multiple GHC and resolvers

### ISSUE THREAD

**Issue by jpvillaisaza** [MercuryTechnologies/slack-web#56]
(This might mean changing from CircleCI to Travis CI.)

**Comment by emmanueltouzery** [comment]
the nice thing is hackage apparently does it on package upload, for a bunch of GHC versions:
https://matrix.hackage.haskell.org/package/slack-web

and of course stackage is doing it also when the package is published, for their nightly setup.

but yeah on package upload to hackage is too late to be doing it. Won't have time to work on that myself though.
