### ISSUE TITLE
Lookup user by email

### ISSUE THREAD

**Issue by jkeuhlen** [MercuryTechnologies/slack-web#78]
It looks like slack has a way to [lookup users by email](https://api.slack.com/methods/users.lookupByEmail) to return the rest of the user object, but it isn't exposed in this library right now. 

The current user object also appears to be missing a fair number of fields: 
![image](https://user-images.githubusercontent.com/10284802/64454665-c8980580-d0a8-11e9-92b8-fb4abc17f0e4.png)

Would you be open to a PR to add support for that user method and extra user fields?

**Comment by jpvillaisaza** [comment]
@jkeuhlen Yes! Thanks!

**Comment by jkeuhlen** [comment]
Closed with #79
