### ISSUE TITLE
Support Conversations API and then deprecate some legacy APIs

### ISSUE THREAD

**Issue by igrep** [MercuryTechnologies/slack-web#82]
Ref: https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

`channels.*`, `groups.*`, `im.*`, and `mpim.*` will be unavailable after February 24th, 2021.

> - The final date for existing apps is now February 24th, 2021.
> - We'll stop allowing newly created Slack apps to use these deprecated APIs beginning June 10th, 2020.
> - All channels.*, groups.*, im.*, & mpim.* methods will return deprecation warnings beginning June 10th, 2020.

**Comment by jpvillaisaza** [comment]
@igrep Thanks for reporting!

Is this something you're interested in working on?

**Comment by igrep** [comment]
Yes, I'm working on this once per week now.

**Comment by igrep** [comment]
Forgot to close this.
