### ISSUE TITLE
Update Hackage Version

### ISSUE THREAD

**Issue by JuanGalilea** [MercuryTechnologies/slack-web#85]
Latest version in hackage is slack-web-0.2.0.11 which was uploaded at 2019-03-01

**Comment by jpvillaisaza** [comment]
Thanks.

I can upload the latest version, but I'll have to review the recent changes, I'm not sure whether 0.2.0.12 (current version in the Cabal file) is correct.

**Comment by jpvillaisaza** [comment]
The latest versions are now in Hackage:

* https://hackage.haskell.org/package/slack-web-0.2.0.12
* https://hackage.haskell.org/package/slack-web-0.2.1.0
