### ISSUE TITLE
Transfer maintainership

### ISSUE THREAD

**Issue by jpvillaisaza** [MercuryTechnologies/slack-web#96]
There are some comments about this in issues and pull requests, so I'm opening this issue to organize notes about transferring the library in one place. Here's a list of previous comments:

* https://github.com/jpvillaisaza/slack-web/pull/93#issuecomment-1234222166
* https://github.com/jpvillaisaza/slack-web/issues/94#issuecomment-1253937893

In summary, I'm looking for someone else to take over this library (different maintainer or owner). As mentioned by @lf-, @MercuryTechnologies can do this and has some plans about it (see #94 for more details).

I'm opening this issue to continue the conversation here and complete the process, and also in case anyone else has comments about it (in particular @igrep or @emmanueltouzery, current GitHub collaborators and Hackage maintainers).

**Comment by emmanueltouzery** [comment]
yes, i have no time for this and i'm not using the library anymore, so it's ok if you strip me of the rights. Thank you for the work @jpvillaisaza !

**Comment by igrep** [comment]
Thanks for mentioning. I'm still using this library for [our slack-log app](https://github.com/haskell-jp/slack-log/), but I'm not developing both the app and slack-web. So I'm glad that lf- and MercuryTechnologies take over. Thank you!

**Comment by jpvillaisaza** [comment]
@lf- Let me know if there's anything else to confirm on your side or if we're ready to continue with the transfer. Thanks!

**Comment by lf-** [comment]
It's good on my side :)

**Comment by lf-** [comment]
My hackage username is `jade` :)

**Comment by jpvillaisaza** [comment]
@lf- Okay, I added you as maintainer in Hackage. Is transferring the repository the next step? Also, can you confirm that it should be to your account?

**Comment by lf-** [comment]
Yep, transfer it to my account and then I can get it moved to Mercury

**Comment by jpvillaisaza** [comment]
Done! Thanks!

**Comment by lf-** [comment]
Alright, got all the GitHub shenanigans done. Thanks! :)
